import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, GitBranch, History, LoaderCircle, Plus, Rocket, RotateCcw, Trash2, X } from 'lucide-react';
import { api } from '../api/client';
import type { Project, ProjectVersion } from '../types';
import { useConfirm, useToast } from './ui/DialogProvider';

export function ProjectVersions({project,onClose,onRestored,onPublished}:{project:Project;onClose:()=>void;onRestored:()=>Promise<void>;onPublished:(project:Project)=>void}){
  const confirm=useConfirm(); const toast=useToast();
  const [versions,setVersions]=useState<ProjectVersion[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [creating,setCreating]=useState(false);
  const [draft,setDraft]=useState({version:'',bump:'auto' as 'auto'|'major'|'minor'|'patch',label:'',notes:''});
  const load=useCallback(async()=>{setLoading(true);try{setVersions(await api.projectVersions(project.id));}finally{setLoading(false);}},[project.id]);
  useEffect(()=>{void load();},[load]);

  async function createVersion(){setBusy(true);try{const created=await api.createProjectVersion(project.id,{version:draft.version||undefined,bump:draft.bump,label:draft.label||undefined,notes:draft.notes||undefined});setVersions(current=>[created,...current]);setDraft({version:'',bump:'auto',label:'',notes:''});setCreating(false);toast(`Versión ${created.version} guardada.`,'success');}catch(error){toast(error instanceof Error?error.message:'No se pudo guardar la versión.','error');}finally{setBusy(false);}}
  async function restore(version:ProjectVersion){if(!await confirm({message:`¿Restaurar la versión ${version.version}? Se creará un respaldo automático del estado actual antes de volver.`,confirmLabel:'Restaurar versión'}))return;setBusy(true);try{const result=await api.restoreProjectVersion(project.id,version.id);await onRestored();await load();toast(result.message,'success');}catch(error){toast(error instanceof Error?error.message:'No se pudo restaurar.','error');}finally{setBusy(false);}}
  async function publish(version:ProjectVersion){if(!await confirm({message:`¿Publicar la versión ${version.version}? El preview público quedará fijado en este snapshot.`,confirmLabel:'Publicar'}))return;setBusy(true);try{await api.publishProjectVersion(project.id,version.id);const updated=await api.updateProject(project.id,{is_public:true});onPublished(updated);await load();toast(`Versión ${version.version} publicada.`,'success');}catch(error){toast(error instanceof Error?error.message:'No se pudo publicar la versión.','error');}finally{setBusy(false);}}
  async function remove(version:ProjectVersion){if(!await confirm({message:`¿Eliminar la versión ${version.version}?`,danger:true,confirmLabel:'Eliminar'}))return;setBusy(true);try{await api.deleteProjectVersion(project.id,version.id);setVersions(current=>current.filter(item=>item.id!==version.id));toast(`Versión ${version.version} eliminada.`,'success');}catch(error){toast(error instanceof Error?error.message:'No se pudo eliminar la versión.','error');}finally{setBusy(false);}}

  return <section className="versions-panel">
    <header><div className="versions-title"><span><GitBranch size={17}/></span><div><small>Control de cambios</small><h2>Versiones de {project.name}</h2><p>Guarda puntos estables, restaura sin miedo y decide qué versión está publicada.</p></div></div><button className="icon-button" onClick={onClose}><X size={17}/></button></header>
    <div className="versions-summary"><div><strong>{versions[0]?`v${versions[0].version}`:'Sin versión'}</strong><span>Última versión</span></div><div><strong>{versions.length}</strong><span>Snapshots guardados</span></div><div><strong>{versions.find(item=>item.is_published)?`v${versions.find(item=>item.is_published)?.version}`:'—'}</strong><span>Versión publicada</span></div><button className="button primary" onClick={()=>setCreating(!creating)}><Plus size={15}/>Guardar versión</button></div>
    {creating&&<div className="version-create-card"><div className="version-create-head"><div><strong>Nueva versión</strong><small>El sistema detecta si el cambio es estructural o solamente un ajuste.</small></div><button onClick={()=>setCreating(false)}><X size={14}/></button></div><div className="version-form-grid"><label><span>Numeración</span><select value={draft.bump} onChange={e=>setDraft({...draft,bump:e.target.value as typeof draft.bump})}><option value="auto">Automática recomendada</option><option value="patch">Patch · 1.0.1</option><option value="minor">Minor · 1.1.0</option><option value="major">Major · 2.0.0</option></select></label><label><span>Versión manual opcional</span><input value={draft.version} onChange={e=>setDraft({...draft,version:e.target.value})} placeholder="Ej. 2 o 1.1.1"/></label><label className="wide"><span>Nombre de esta entrega</span><input value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})} placeholder="Ej. Formularios de clientes listos"/></label><label className="wide"><span>Notas</span><textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} rows={2} placeholder="Qué cambió y por qué…"/></label></div><div className="version-create-actions"><button className="button ghost" onClick={()=>setCreating(false)}>Cancelar</button><button className="button primary" disabled={busy} onClick={()=>void createVersion()}>{busy?<LoaderCircle size={14} className="spin"/>:<CheckCircle2 size={14}/>}Crear snapshot</button></div></div>}
    <div className="versions-list">{loading?<div className="versions-empty"><LoaderCircle className="spin"/><span>Cargando historial…</span></div>:versions.length===0?<div className="versions-empty"><History size={34}/><strong>Todavía no hay versiones</strong><span>Guarda la primera cuando el proyecto tenga un estado que quieras conservar.</span></div>:versions.map((version,index)=><article key={version.id} className={`version-item ${version.is_published?'published':''}`}><div className="version-rail"><i/>{index<versions.length-1&&<span/>}</div><div className="version-card"><div className="version-card-head"><div><strong>v{version.version}</strong>{index===0&&<em>Última</em>}{version.is_published&&<em className="published"><Rocket size={10}/>Publicada</em>}</div><time>{new Date(version.created_at).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})}</time></div><h3>{version.label||'Snapshot del proyecto'}</h3>{version.notes&&<p>{version.notes}</p>}<div className="version-changes">{Object.entries(version.change_summary??{}).map(([key,item])=><span key={key}><b>{item.total}</b> {item.label}{item.delta!==0&&<i className={item.delta>0?'up':'down'}>{item.delta>0?'+':''}{item.delta}</i>}</span>)}</div><div className="version-actions"><button disabled={busy} onClick={()=>void restore(version)}><RotateCcw size={13}/>Restaurar</button><button disabled={busy||version.is_published} onClick={()=>void publish(version)}><Rocket size={13}/>{version.is_published?'Publicada':'Publicar'}</button><button className="danger" disabled={busy||version.is_published} onClick={()=>void remove(version)}><Trash2 size={13}/></button></div></div></article>)}</div>
  </section>;
}
